name: Extension Builder

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: 
      - master
  pull_request:

jobs:

  test-javascript-libraries:
    name: Test the Javascript libraries
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: browser-extensions/common/js

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure node v12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install test framework dependencies
        run: npm install

      - name: Run tests
        run: npm run test-with-coverage

  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-extension:
    # Name the Job
    name: Build the extension
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ["chrome", "firefox"]

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure node v12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install web-ext tooling
        run: npm install -g web-ext

      # Runs a script
      - name: Build ${{ matrix.browser }} Extension
        run: |
          echo "Building extension for ${{ matrix.browser }} at `date`"
          # Make the build script executable
          chmod +x ./build/extension-${{ matrix.browser }}/build.sh
          # Build the extension
          ./build/extension-${{ matrix.browser }}/build.sh
        shell: bash
        env:
          EXTENSION_BUILD_ID: ${{ github.run_number }}

      - name: Upload build extension package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.browser }}-extension-package
          path: browser-extensions/${{ matrix.browser }}/build/web-ext-artifacts/running_challenges-*.zip

  integration-test:
    name: Selenium
    runs-on: ubuntu-latest
    needs: 
      - build-extension
      - test-javascript-libraries
    strategy:
      matrix:
        # browser: ["chrome", "firefox"] # We'll get to firefox at some point, lets start with Chrome
        include:
          - browser: "chrome"
            selenium-image: selenium/standalone-chrome:101.0
          # - browser: "firefox"
          #   selenium-image: selenium/standalone-firefox:latest
      fail-fast: false
    # services:
    #  # We can choose to not specify the port, and GH Actions will tell us wht the port is if we want - probably wise.
    #   selenium:
    #     image: ${{ matrix.selenium-image }}
    #     ports: 
    #       - 4444:4444
    #     volumes:
    #       - /dev/shm:/dev/shm
    defaults:
      run:
        shell: bash
        working-directory: browser-extensions/common/js

    steps:

      # Checks out a copy of the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Get previously built packages
      - name: Download all built extension packages
        uses: actions/download-artifact@v2
        with:
          path: browser-extensions/common/js/extension-binaries

      - name: Show built extension packages
        run: ls -lR extension-binaries

      - name: Configure node v12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install test framework dependencies
        run: npm install

      - name: Run selenium test for ${{ matrix.browser }}
        run: |

          echo "Creating a certificate"
          cd test-selenium/mock-parkrun-sites/nginx/cert/
          bash generate.sh
          cd -

          echo "Starting up docker compose services"
          docker-compose -f test-selenium/docker-compose.yml up -d

          # Wait for things to have started up
          sleep 30

          # Curl our nginx server just to check things are working
          # curl -k http://www.parkrun.org.uk/parkrunner/1309364/all/

          echo ${EXTENSION_PATH}
          ls -lh ${EXTENSION_PATH}
          # Find the extension zip in the path supplied
          export EXTENSION_ZIP=$(ls ${EXTENSION_PATH}/*.zip | head -n 1)
          echo "Extension found at ${EXTENSION_ZIP}"
          echo "Running selenium-docker.js against ${{ matrix.browser }}"
          npm run test-selenium

          # Stop the docker containers
          docker-compose -f test-selenium/docker-compose.yml down
        env:
          EXTENSION_PATH: extension-binaries/${{ matrix.browser }}-extension-package/
          EXTENSION_BROWSER: ${{ matrix.browser }}
          SELENIUM_PORT: 4444
          COUNTRY_FILTER: parkrun.org.uk,parkrun.com.de # Just a couple to begin with, until it is working!

      - name: Upload test screenshots
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.browser }}-screenshots
          path: browser-extensions/common/js/screenshots/
        if: always()


  # This stage will run once the extensions have been built, and should only run if they were successful.
  # Assuming they are successful, we will push them somewhere they can be used.

  # If we are on the master branch, and it is tagged as a release versino, we should create a release
  publish-extension:
    name: Push the build extensions somewhere
    runs-on: ubuntu-latest
    needs: 
      - integration-test
    # if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download all built extension packages
        uses: actions/download-artifact@v2
        with:
          path: extension-binaries

      - name: Show built extension packages
        run: ls -lR extension-binaries

      - id: get-branch-version-tag
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context)
            console.log(context.ref)
            console.log(github.ref)
            // This script will create a release, and upload our files and release notes to it
            if (!"${{ github.ref }}".startsWith('refs/tags/v')) {
              return
            }
            // Find the version tag
            var version_tag = github.ref.replace("refs/tags/", "")
            console.log(version_tag)
            // Store it in the step output variables
            core.setOutput('version_tag', version_tag)

            /*
            // TODO: Do we need to check if this release already exists?

            // Create a release
            github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: version_tag,
              name: <name of the release>,
              body: <text for the release>,
              draft: false,
              prelease: false,
            })

            // Upload all the artifacts to it
            github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ...
            })
            */
        # if: startsWith(github.ref, 'refs/tags/v')
 

      # - id: get-branch-version-tag
      #   uses: actions/github-script@v4
      #   with:
      #     script: |
      #       var version_tag = ''
      #       if (github.ref.startsWith('refs/tags/v')){
      #         version_tag = github.ref.split('/')[2]
      #       }
      #       core.setOutput('version_tag', version_tag)
      #   if: startsWith(github.ref, 'refs/tags/v')

      - run: echo "branch version tag is ${{steps.get-branch-version-tag.outputs.version_tag}}"
        # if: startsWith(github.ref, 'refs/tags/v')

      # We might be able to use the github script action instead of this to script what we need to do in one go
      - name: Create release
        uses: softprops/action-gh-release@v1 # Read the docs here: https://github.com/softprops/action-gh-release
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: Running Challenges ${{steps.get-branch-version-tag.outputs.version_tag}}
          files: "extension-binaries/*/running_challenges*.zip"
          body: |
            Release notes go here
          # body_path: Auto/manually generated file for release notes goes here
          fail_on_unmatched_files: True
          draft: True # We'll move it to release when it's all tested and known to be working
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
